name: video_player_for_web_integration_tests
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player_platform_interface:
    git:
      url: https://github.com/Minhan39/packages.git
      path: packages/video_player_platform_interface
      ref: main
  video_player_web:
    path: ../
  web: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
